version: "3"
services: 

  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - "1111:8080"
      - "1000:1000"
    container_name: jenkins
    
    volumes: 
      - /home/apps/jenkins:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    links:
      - artifactory 
      - sonarqube
  artifactory:
    image: mattgruter/artifactory
    ports:
      - "9090:8080"
    container_name: artifactory
    volumes: 
      - /home/apps/artifactory:/artifactory:rw
      
  sonarqube:
    image: sonarqube:6.7-alpine
    ports:
      - 9000:9000
      - 9092:9092
    container_name: sonarqube
    volumes:
      - /home/apps/sonarqube/data:/opt/sonarqube/data 
      - /home/apps/sonarqube/extensions:/opt/sonarqube/extensions 
